// Generated by CoffeeScript 1.6.2
(function() {
  (function($) {
    return $.fn.slidecast = function() {
      return this.each(function() {
        var audioElement, offset, slides, tid, update;

        slides = [];
        offset = 0;
        $('.slide', this).hide().each(function() {
          var duration;

          slides.push({
            time: offset,
            element: this
          });
          duration = parseInt($(this).data('duration'));
          return offset += duration;
        });
        audioElement = $(this).find('audio').get(0);
        tid = null;
        update = function() {
          var i, t;

          t = Math.floor(1000 * audioElement.currentTime);
          i = slides.length - 1;
          while (t < slides[i].time) {
            i--;
          }
          $('#presentation .slide').hide();
          $(slides[i].element).show();
          clearTimeout(tid);
          tid = null;
          if (i < slides.length - 1) {
            tid = setTimeout(update, 1000 * (slides[i].time - t));
          }
        };
        update();
        return $('audio', this).on('playing pause seeked', update);
      });
    };
  })(jQuery);

}).call(this);
